input: 
  sample table: inputs/samples.tsv
  adapter_file: inputs/all_illumina_adapters.fa
  thermus_genome: inputs/Thermus_genome/Thermus_thermophilus_ATCC_BAA_163.fasta

  nodes_file: /orcd/data/chisholm/002/hstor001/bioinfo/projects/25_ProSynTaxDB/ProSynTaxDB_final/genomes/final_genome_files/final_ProSynTax_nodes.dmp
  names_file: /orcd/data/chisholm/002/hstor001/bioinfo/projects/25_ProSynTaxDB/ProSynTaxDB_final/genomes/final_genome_files/final_ProSynTax_names.dmp
  fmi_file: /orcd/data/chisholm/002/hstor001/bioinfo/projects/25_ProSynTaxDB/ProSynTaxDB_final/genomes/final_genome_files/ProSynTaxDB_v1.2.fmi
  
  cycog_file: inputs/cycog_len.tsv
  diamond_file: /pool001/jmullet/blast/cycog6/CyCOG6.dmnd

classification_summary:
  # list of genus to extract read count for (remaining genus will be summed into "other_genus")
  genus_list: ['Synechococcus', 'Prochlorococcus', 'unclassified', 'Viruses']

scratch directory: scratch
results directory: results
